### ISSUE TITLE
slime-help: issue displaying a docstring with references to macros

### ISSUE THREAD

**Issue by vindarel** [mmontone/slime-doc-contribs#4]
Hi,

I am trying to enhance a docstring:

```
(setf (documentation 'defmacro 'function)
         "Example macros: IF WITH-OPEN-FILE UNWIND-PROTECT DEFUN LOOP")
```

Calling `slime-help-symbol` (C-c C-d d) either gives me "Don't know how to format" or it displays "Example macros: " without the rest.

**Comment by mmontone** [comment]
I've "fixed" this. The problem is some of those are "special operators", like IF and UNWIND-PROTECT. But as the backend does not retrieve info for those, I just show in plain-text.

**Comment by vindarel** [comment]
Thank you!

**Comment by mmontone** [comment]
Now that I look closer, SBCL returns docs for special operators:
```
CL-USER> (documentation 'unwind-protect 'function)
"UNWIND-PROTECT protected cleanup*

Evaluate the form PROTECTED, returning its values. The CLEANUP forms are
evaluated whenever the dynamic scope of the PROTECTED form is exited (either
due to normal completion or a non-local exit such as THROW)."
CL-USER> (documentation 'progn 'function)
"PROGN form*

Evaluates each FORM in order, returning the values of the last form. With no
forms, returns NIL."
```

So, I'll try to make slime-help show docs for them.

**Comment by mmontone** [comment]
I've implemented support for special operators

![imagen](https://user-images.githubusercontent.com/436110/192648186-9cb6e843-76d8-4256-b470-301e716bff2c.png)
